version: "3"

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  backend:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    ports:
      - 5000:5000